# Site settings
title: Yu Cheng Homepage
description: Yu Cheng Homepage.
baseurl: ""
url: "https://yucheng-03.github.io"
og_image: /assets/img/profile-2022.JPG
google_analytics: "UA-121636368-3"

# 包含的文件列表
include:
  - thoughts.html

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: Thoughts
    

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: chengusanye@gmail.com
      link: mailto:chengusanye@gmail.com
    - name: Wechat
      value: Chengy_ustc
      link: /assets/img/wechat-qr-code.png
  follow:
    - name: GitHub
      link: http://github.com/yucheng-03

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1